project:
  type: website
  output-dir: docs

website:
  title: "HP2"
  navbar:
    background:  primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - hp2-nadiasharapova.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    page-layout: full

editor: visual

